//
//   QuestionBank.swift
//  Quiz.io
//
//  Created by AnonyMac on 25/4/2561 BE.
//  Copyright © 2561 Chanon Treemeth. All rights reserved.
//

import Foundation
class QuestionBank {
    var list = [Question]()
    
    init() {        
        list.append(Question(image: "cat", questionText: "สัตว์ในรูปนี้คือตัวอะไร ?", choiceA: "1. สุนัข", choiceB: "2. เป็ด", choiceC: "3. นก", choiceD: "4. เห็ด", answer: 2))
        list.append(Question(image: "paper", questionText: "กระดาษ 1 รีม มีทั้งหมดกี่แผ่น ?", choiceA: "1. 450", choiceB: "2. 460", choiceC: "3. 470", choiceD: "4. 480", answer: 4))
        list.append(Question(image: "anesthetic", questionText: "ยาสลบทำจากอะไร ?", choiceA: "1. amitryptylin", choiceB: "2. sildenafil", choiceC: "3. procodyl", choiceD: "4. chloroform", answer: 4))
        list.append(Question(image: "blood", questionText: "ในทางเคมี สารที่มีคุณสมบัติใกล้เคียงกับเลือดมนุษย์มากที่สุดคืออะไร ?", choiceA: "1. น้ำทะเล", choiceB: "2. น้ำเปล่า", choiceC: "3. ด่างทับทิม", choiceD: "4. น้ำผึ้ง", answer: 1))
        list.append(Question(image: "toothpaste", questionText: "กลิ่นเมนทอลในยาสีฟันทำจากอะไร ?", choiceA: "1. ใบสาระแหน่", choiceB: "2. ใบกะเพรา", choiceC: "3. ขิง", choiceD: "4. ใบมะกรูด", answer: 1))
        list.append(Question(image: "poseidon", questionText: "โพไซดอน เป็นเทพเจ้าแห่งทะเลของใคร ?", choiceA: "1. โรมัน", choiceB: "2. กรีก", choiceC: "3. อียิปต์", choiceD: "4. เมโสโปเตเมีย", answer: 2))
        list.append(Question(image: "drug", questionText: "ตัวยา AZT และ DDI ใช้รักษาโรคอะไร ?", choiceA: "1. เอดส์", choiceB: "2. ไมเกรน", choiceC: "3. ลำไส้อักเสบ", choiceD: "4. พิษสุนัขบ้า", answer: 1))
        list.append(Question(image: "question_mark", questionText: "เลขของโรมัน M เท่ากับจำนวนเลขอะไร ?", choiceA: "1. 10", choiceB: "2. 100", choiceC: "3. 1,000", choiceD: "4. 10,000", answer: 3))
        list.append(Question(image: "wine", questionText: "ไวน์ของรัฐใดในสหรัฐฯถือว่าดีที่สุด ?", choiceA: "1. แคลิฟอร์เนีย", choiceB: "2. ฟลอริด้า", choiceC: "3. เท็กซัส", choiceD: "4. มิชิแกน", answer: 1))
        list.append(Question(image: "mirror", questionText: "ด้านหลังของกระจกส่องหน้าใช้อะไรเคลือบ ?", choiceA: "1. ฟอยด์", choiceB: "2. นิกเกิล", choiceC: "3. ปรอท", choiceD: "4. รูบิเดียม", answer: 3))
        list.append(Question(image: "monalisa", questionText: "ใครคือผู้เขียนภาพโมนาลิซ่า ?", choiceA: "1. วินเซน แวนโกะ", choiceB: "2. ลีโอนาโด ดาวินชี", choiceC: "3. ไมเคิลแองเจลโล", choiceD: "4. ปาโบล ปิกัสโซ", answer: 2))
        list.append(Question(image: "question_mark", questionText: "“ทักทาย” ใช้คำราชาศัพท์ว่า ?", choiceA: "1. ทรงทักทาย", choiceB: "2. ทรงตรัส", choiceC: "3. ทรงปราศรัย", choiceD: "4. ทรงมีพระราชปฏิสันถาร", answer: 4))
        list.append(Question(image: "skull", questionText: "กระดูกในตัวคนมีกี่ชิ้น ?", choiceA: "1. ชิ้นสองชิ้น", choiceB: "2. หลายชิ้น", choiceC: "3. 188 ชิ้น", choiceD: "4. 208 ชิ้น", answer: 4))
        list.append(Question(image: "cobra", questionText: "งูใดในเอเชียมีพิษร้ายแรงที่สุด ?", choiceA: "1. งูเห่า", choiceB: "2. งูสามเหลี่ยม", choiceC: "3. งูจงอาง", choiceD: "4. งูกะปะ", answer: 2))
        list.append(Question(image: "alex", questionText: "บุคคลในภาพ คือใคร ?", choiceA: "1. อเล็กซ์ เฟอร์กูสัน", choiceB: "2. โชเซ่ มูริญโย่", choiceC: "3. เป็ป กวาดิโอล่า", choiceD: "4. เดวิส มอยส์", answer: 1))
        list.append(Question(image: "bnk48", questionText: "BNK48 ตอนนี้มีทั้งหมดกี่คน ?", choiceA: "1. 29 คน", choiceB: "2. 37 คน", choiceC: "3. 42 คน", choiceD: "4. 48 คน", answer: 1))
        list.append(Question(image: "swu", questionText: "มหาวิทยาลัยศรีนครินทรวิโรฒได้รับการสถาปนาใน พ.ศ. ใด  ?", choiceA: "1. พ.ศ. 2492", choiceB: "2. พ.ศ. 2496", choiceC: "3. พ.ศ. 2498", choiceD: "4. พ.ศ. 2517", answer: 4))
        list.append(Question(image: "worm", questionText: "ไส้เดือนหายใจทางอะไร ?", choiceA: "1. ผิวหนัง", choiceB: "2. จมูก", choiceC: "3. ปาก", choiceD: "4. ท้อง", answer: 1))
        list.append(Question(image: "fish", questionText: "ปลาอะไรว่ายน้ำได้เร็วที่สุด ?", choiceA: "1. โลมา", choiceB: "2. ฉลาม", choiceC: "3. กระเบน", choiceD: "4. ปลาตะเพียน", answer: 2))
        list.append(Question(image: "dog", questionText: "สุนัขมีฟันกี่ซี่ ?", choiceA: "1. 32 ซี่", choiceB: "2. 36 ซี่", choiceC: "3. 38 ซี่", choiceD: "4. 42 ซี่", answer: 3))
        list.append(Question(image: "eye", questionText: "การกระพริบตาในหนึ่งวันเทียบกับการใช้กล้ามเนื้อขาวิ่งกี่กิโลเมตร ?", choiceA: "1. 30", choiceB: "2. 50", choiceC: "3. 80", choiceD: "4. 100", answer: 3))
        list.append(Question(image: "hair", questionText: "ในร่างกายคน ขนส่วนไหนที่แข็งแรงที่สุด ?", choiceA: "1. ขนหน้าแข็ง", choiceB: "2. ขนแขน  ", choiceC: "3. หนวด ", choiceD: "4. ขนรักแร้", answer: 3))
        list.append(Question(image: "color", questionText: "ตาของคนสามารถแยกแยะสีได้ประมาณกี่สี ?", choiceA: "1. 1,000 สี", choiceB: "2. 1,700 สี ", choiceC: "3. 17,000 สี ", choiceD: "4. 1,700 ล้านสี", answer: 3))
        list.append(Question(image: "sea", questionText: "มีกี่ประเทศในโลกที่ไม่มีชายฝั่งทะเล ?", choiceA: "1. 24 ประเทศ", choiceB: "2. 25 ประเทศ   ", choiceC: "3. 26 ประเทศ  ", choiceD: "4. 27 ประเทศ", answer: 3))
        list.append(Question(image: "statue", questionText: "พระบรมราชานุสาวรีย์ของกษัตริย์พระองค์ ใดประดิษฐานหน้าตึกรัฐสภา?", choiceA: "1. รัชกาลที่ 5", choiceB: "2. รัชกาลที่ 6", choiceC: "3. รัชกาลที่ 7", choiceD: "4. รัชกาลที่ 9", answer: 3))
        list.append(Question(image: "labor", questionText: "การใช้แรงงานเด็กมีมากในทวีปใด ?", choiceA: "1. ยุโรป", choiceB: "2.ออสเตรเลีย", choiceC: "3.แอฟริกา", choiceD: "4. เอเชีย", answer: 4))
        list.append(Question(image: "question_mark", questionText: "'ดินแดนแห่งแกะ' เป็นสมญานามของประเทศใด ?", choiceA: "1. ออสเตรเลีย ", choiceB: "2. นิวซีแลนด์", choiceC: "3. ตุรกี", choiceD: "4. ฝรั่งเศส", answer: 1))
        list.append(Question(image: "question_mark", questionText: "ระบบรัฐสภาของไทยจำลองมาจากประเทศใด ?", choiceA: "1. อังกฤษ", choiceB: "2. USA", choiceC: "3. สเปน", choiceD: "4. อิตาลี", answer: 1))
        list.append(Question(image: "paracetamol", questionText: "หากกินยาพาราเซตามอลมากเกินไปจะทำลายอวัยวะส่วนใด ?", choiceA: "1. ไต", choiceB: "2. หัวใจ", choiceC: "3. ปอด", choiceD: "4. ตับ", answer: 4))
        list.append(Question(image: "atom", questionText: "โจเซฟ พริสต์ลีย์พบอะไร ?", choiceA: "1. ออกซิเจน", choiceB: "2. คาร์บอนไดออกไซด์", choiceC: "3. คาบอนมอนออกไซด์", choiceD: "4. ฮีเลียม", answer: 1))
        list.append(Question(image: "question_mark", questionText: "นกอะไรมีรูจมูกอยู่ที่ปลายจะงอยปาก ?", choiceA: "1. นกกีวี", choiceB: "2. นกฟามิงโก้", choiceC: "3. นกเค้าแมว", choiceD: "4. นกนางแอ่น", answer: 1))
        list.append(Question(image: "color", questionText: "คู่สีอะไรมีผลต่อการมองมากที่สุด ?", choiceA: "1. ดำกับขาว", choiceB: "2. เหลืองกับดำ", choiceC: "3. แดงกับเขียว", choiceD: "4. เหลืองกับน้ำเงิน", answer: 2))
        list.append(Question(image: "gun", questionText: "ชาติ ไหนสอนไทยให้หล่อปืนใหญ่ ?", choiceA: "1. โปรตุเกส", choiceB: "2. ญี่ปุ่น", choiceC: "3. จีน", choiceD: "4. ฝรั่งเศส", answer: 1))
        list.append(Question(image: "egypt", questionText: "ชาวอียิปต์ โบราณนับถือสัตว์เลี้ยงตัวใดดุจเทพเจ้า ?", choiceA: "1. หมา", choiceB: "2. สิงโต", choiceC: "3. แมว", choiceD: "4. เสือ", answer: 3))
        list.append(Question(image: "subway", questionText: "รถไฟใต้ดินแห่งแรกสร้างขึ้นที่ไหน ?", choiceA: "1. ลอนดอน", choiceB: "2. โตเกียว", choiceC: "3. โรม", choiceD: "4. ปารีส", answer: 1))
        list.append(Question(image: "rainbow", questionText: "เห็นรุ้งกินน้ำเต็มวงได้อย่างไร ?", choiceA: "1. มองจากเครื่องบิน", choiceB: "2. มองระหว่างตึก", choiceC: "3. มองขณะฝนตก", choiceD: "4. มองผ่านกระจก", answer: 1))
        list.append(Question(image: "american_football", questionText: "กีฬารักบี้ใช้ผู้เล่นข้างละกี่คน ?", choiceA: "1. 11 คน", choiceB: "2. 12 คน", choiceC: "3. 15 คน", choiceD: "4. 16 คน", answer: 3))
        list.append(Question(image: "blood_type", questionText: "หมู่เลือดที่มีน้อยที่สุดของคนไทยคือหมู่ใด ?", choiceA: "1. เอ", choiceB: "2. เอบี", choiceC: "3. บี", choiceD: "4. โอ", answer: 2))
        list.append(Question(image: "fish", questionText: "เราจะรู้ได้อย่างไรว่าปลามีอายุเท่าใด?", choiceA: "1. ดูวงเกล็ด", choiceB: "2. ดูเส้นหาง", choiceC: "3. ดูขนาดตัว", choiceD: "4. ดูเหงือก", answer: 1))
        list.append(Question(image: "question_mark", questionText: "ม้าและม้าลายมีวิธีทำตัวให้สะอาดอย่างไร ?", choiceA: "1. กลิ้งกับฝุ่น", choiceB: "2. ลงน้ำ", choiceC: "3. เลียตัว", choiceD: "4. ถูกับต้นไม้", answer: 1))
        list.append(Question(image: "japan", questionText: "เมืองหลวงของญี่ปุ่นคือเมืองใด ?", choiceA: "1. โตเกียว", choiceB: "2. เคียวโตะ", choiceC: "3. ฟุกุโอกะ", choiceD: "4. โยโกฮาม่า", answer: 1))
        list.append(Question(image: "fifa_logo", questionText: "ผู้ตัดสินกีฬาฟุตบอลของฟีฟ่าต้องมีอายุไม่เกินกี่ปี ?", choiceA: "1. 40ปี", choiceB: "2. 45 ปี", choiceC: "3. 50 ปี", choiceD: "4. 55 ปี", answer: 2))
        list.append(Question(image: "question_mark", questionText: "บ้านเลขที่ 99999 คอร์วาตุนตุริ ฟินแลนด์เป็นบ้านของใคร ?", choiceA: "1. อับราฮัม ลินคอร์น", choiceB: "2. จอร์น เอฟ เคนาดี้", choiceC: "3. โดนัล ทรัมป์", choiceD: "4. ซานตาครอส", answer: 4))
        list.append(Question(image: "tiger", questionText: "เสือตัวใดใหญ่ที่สุดในโลก ?", choiceA: "1. เสือดำ", choiceB: "2. เสือโคร่งไซบีเรีย", choiceC: "3. เสือโคร่งเบงกอล", choiceD: "4. เสือสมิง", answer: 2))
        list.append(Question(image: "lizard", questionText: "กิ่งก่าตัวใดใหญ่ที่สุดในโลก ?", choiceA: "1. กิ้งก่าออสเตรเลีย", choiceB: "2. มังกรโคโมโด", choiceC: "3. ตัวเงินตัวทอง", choiceD: "4. กิ้งก่าสวีเดน", answer: 2))
        list.append(Question(image: "soldier", questionText: "เราเรียกทหารเรือฝ่ายบกว่าอะไร ?", choiceA: "1. นาวิกโยธิน", choiceB: "2. SEAL", choiceC: "3. REACON", choiceD: "4. ทหารบก", answer: 1))
        list.append(Question(image: "cross", questionText: "สถานที่ฝังศพของอิสลามิกชนเรียกว่าอะไร ?", choiceA: "1. กูโบ", choiceB: "2. โลงศพ", choiceC: "3. กูเบียน", choiceD: "4. กล่อง", answer: 1))
        list.append(Question(image: "question_mark", questionText: "เทพเจ้าของชาวสวีเดนและนอร์เวคือใคร ?", choiceA: "1. ธอร์", choiceB: "2. ซีอุส", choiceC: "3. โอดิน", choiceD: "4. ธานอส", answer: 3))
        list.append(Question(image: "knight", questionText: "'เซอร์' คำเติมหน้าชื่อขุนนางชั้นอัศวินของชาติ ใด ?", choiceA: "1. อังกฤษ", choiceB: "2. USA", choiceC: "3. ฝรั่งเศส", choiceD: "4. อิตาลี", answer: 1))
        list.append(Question(image: "hiv", questionText: "โรคเอดส์ถูกพบครั้งแรกที่ไหน ?", choiceA: "1. อังกฤษ", choiceB: "2. USA", choiceC: "3. ฝรั่งเศส", choiceD: "4. อิตาลี", answer: 2))
        list.append(Question(image: "atom", questionText: "เซอร์ วิลเลียมแรม พบอะไร ?", choiceA: "1. นิเกล", choiceB: "2. โคเมียม", choiceC: "3. ฮีเลียม", choiceD: "4. ไนโตรเจน", answer: 1))
        list.append(Question(image: "shoe", questionText: "ฟิลิป ไนท์ ก่อตั้งบริษัทผลิตรองเท้ายี่ห้อใด ?", choiceA: "1. ไนกี้", choiceB: "2. อดิดาส", choiceC: "3. พูม่า", choiceD: "4. ลาครอส", answer: 1))
        list.append(Question(image: "ship", questionText: "ชาติ ใดเป็นชาติแรกที่เดินเรือ ?", choiceA: "1. อียิปต์โบราณ", choiceB: "2. จีน", choiceC: "3. กรีก", choiceD: "4. โปรตุเกส", answer: 1))
        list.append(Question(image: "rome", questionText: "กรุงโรมยิ่งใหญ่ในยุคสมัยของใคร ?", choiceA: "1. จูเลียส ซีซาร์", choiceB: "2. พระเจ้าคอนสแตนตินที่ 1", choiceC: "3. พระเจ้าคอนสแตนตินที่ 2", choiceD: "4. พระเจ้าคอนสแตนตินที่ 3", answer: 1))
        list.append(Question(image: "question_mark", questionText: "ประเทศใดกินปลามากที่สุด ?", choiceA: "1. ญี่ปุ่น", choiceB: "2. ไทย", choiceC: "3. จีน", choiceD: "4. อังกฤษ", answer: 1))
        list.append(Question(image: "question_mark", questionText: "ปลากะโห้ถูกพบครั้งแรกที่ไหน ?", choiceA: "1. ญี่ปุ่น", choiceB: "2. ไทย", choiceC: "3. จีน", choiceD: "4. อังกฤษ", answer: 2))
        list.append(Question(image: "venus", questionText: "ทุก ๆ กี่ปีดาวศุกร์จะโคจรเข้าใกล้โลกมากที่สุด ?", choiceA: "1. 8 ปี", choiceB: "2. 9 ปี", choiceC: "3. 10 ปี", choiceD: "4. 29 ปี", answer: 1))
        list.append(Question(image: "number", questionText: "เลขที่ถือว่าโชคดีที่สุดของชาวอิตาลีคือเลขใด ?", choiceA: "1. 6", choiceB: "2. 7", choiceC: "3. 9", choiceD: "4. 13", answer: 4))
        list.append(Question(image: "prayuth", questionText: "คนในรูปคือใคร ?", choiceA: "1. พลเอก ประยุทธ์ จันทร์โอชา", choiceB: "2. พลเอก ประยุทธ์ จันทร์โอเช", choiceC: "3. พลเอก ประหยัด จันทร์อังคารพุธ", choiceD: "4. พลเอก ปลาหยุด จันทร์โอฬาร", answer: 1))
        list.append(Question(image: "blackpenther", questionText: "ใครฆ่าเสือดำ ?", choiceA: "1. เปรมชัย", choiceB: "2. ครูปรีชา", choiceC: "3. เพื่อนเปรมชัย", choiceD: "4. หาคำตอบไม่ได้", answer: 4))
        list.append(Question(image: "copper", questionText: "ประเทศใดผลิตทองแดงมากที่สุด  ?", choiceA: "1. ชิลี", choiceB: "2. สหรัฐอเมริกา", choiceC: "3. อังกฤษ", choiceD: "4. สเปน", answer: 2))
        list.append(Question(image: "question_mark", questionText: "รัฐบุรุษอาวุโสคนแรกของไทยคือใคร ?", choiceA: "1. นายประยุทธ์ จันโอชา", choiceB: "2. นายปรีดี พนมยงค์", choiceC: "3. นายอภิสิทธิ์ เวชชาชีวะ", choiceD: "4. นายทักษิณ ชินวัตร", answer: 2))
        list.append(Question(image: "thai_flag", questionText: "ธงไตรรงค์มีใช้ในรัชสมัยใดเป็นครั้งแรก ?", choiceA: "1. รัชกาลที่ 5", choiceB: "2. รัชกาลที่ 6", choiceC: "3. รัชกาลที่ 7", choiceD: "4. รัชกาลที่ 8", answer: 2))
        list.append(Question(image: "question_mark", questionText: "กำหนดให้วันที่ 1 มกราคม เป็นวันขึ้นปีใหม่แทนวันสงกรานต์ในรัชสมัยใดเป็นครั้งแรก ?", choiceA: "1. รัชกาลที่ 6", choiceB: "2. รัชกาลที่ 7", choiceC: "3. รัชกาลที่ 8", choiceD: "4. รัชกาลที่ 9", answer: 3))
        list.append(Question(image: "question_mark", questionText: "วรรณคดีเรื่องแรกของอยุธยา คือเรื่องอะไร ?", choiceA: "1. ลิลิตพระลอ", choiceB: "2. ขุนช้างขุนแผน", choiceC: "3. พระอภัยมณี", choiceD: "4. ลิลิตโองการแช่งน้ำ", answer: 4))
        list.append(Question(image: "industrial", questionText: "ระบบงานอุตสาหกรรมเริ่มครั้งแรกในประเทศใด ?", choiceA: "1. ญี่ปุ่น", choiceB: "2. อังกฤษ", choiceC: "3. สเปน", choiceD: "4. ฝรั่งเศส", answer: 2))
        list.append(Question(image: "question_mark", questionText: "คัมภีร์แพทย์แผนโบราณมีชื่อเรียกอีกอย่างว่าอะไร ?", choiceA: "1. มัธยมจินดา", choiceB: "2. อนุบาลจินดา", choiceC: "3. ประถมจินดา", choiceD: "4. มหาลัยจินดา", answer: 3))
        list.append(Question(image: "airbag", questionText: "ถุงลมนิรภัยติดตั้งครั้งแรกกับรถยนต์ยี่ห้อใด ?", choiceA: "1. โตโยต้า", choiceB: "2. ไครสเลอร์", choiceC: "3. ฮอนด้า", choiceD: "4. มิตซูบิชิ", answer: 2))
        list.append(Question(image: "question_mark", questionText: "ประเทศใดได้ชื่อจัดการกับขยะดีที่สุดในโลก ?", choiceA: "1. ไทย", choiceB: "2. มาเลเซีย", choiceC: "3. ญี่ปุ่น", choiceD: "4. อังกฤษ", answer: 3))
        list.append(Question(image: "forest", questionText: "ป่าที่พระพุทธเจ้าทรงแสดงปฐมเทศนาคือป่าอะไร ?", choiceA: "1. ป่าอิสิปตนมฤคทายวัน", choiceB: "2. ป่าอิสิปตนมฤคทายทู", choiceC: "3. ป่าอิสิปตนมฤคทายทรี", choiceD: "4. ป่าอิสิปตนมฤคทายโฟร์", answer: 1))
        list.append(Question(image: "question_mark", questionText: "งานวันกาชาดมีครั้งแรกในรัชสมัยใด ?", choiceA: "1. รัชกาลที่ 7", choiceB: "2. รัชกาลที่ 8", choiceC: "3. รัชกาลที่ 9", choiceD: "4. รัชกาลที่ 10", answer: 1))
        list.append(Question(image: "question_mark", questionText: "ผู้นำต่อสู้การเหยียดผิวในอเมริกา ได้รางวัลโนเบล ปี 2507 คือใคร ?", choiceA: "1. โดนัล ทรัมป์", choiceB: "2. มาร์ติน ลูเธอร์ คิง", choiceC: "3. แจคหม่า", choiceD: "4. บารัค โอบาม่า", answer: 2))
        list.append(Question(image: "bird", questionText: "นกไนติงเกล ได้ชื่อว่าร้องเพลงไพเราะ เป็นนกจำพวกไหน ?", choiceA: "1. นกกระจอก", choiceB: "2. นกกางเขน", choiceC: "3. นกกระจอกเทศ", choiceD: "4. นกอินทรี", answer: 2))
        list.append(Question(image: "question_mark", questionText: "ทำไมสเปนเลือก 12 ตุลาคมของทุกปีเป็นวันชาติ ?", choiceA: "1. วันที่ค้นพบประเทศสเปน", choiceB: "2. วันที่มีผู้ปกครองคนแรก", choiceC: "3. วันที่มีกฎหมายใช้วันแรก", choiceD: "4. วันที่โคลัมบัสพบทวีปอเมริกา เปรียบเสมือนการค้นพบโลกโหม่", answer: 4))
        list.append(Question(image: "question_mark", questionText: "ประเทศใดในยุโรปใหญ่เป็นอันดับ 3 รองจากประเทศรัสเซีย และประเทศฝรั่งเศส ?", choiceA: "1. จีน", choiceB: "2. ฝรั่งเศส", choiceC: "3. แอฟฟริกา", choiceD: "4. สเปน", answer: 4))
        list.append(Question(image: "question_mark", questionText: "จังหวัดใดได้ชื่อมีพื้นที่ปลูกปาล์มน้ำมันมากที่สุด ?", choiceA: "1. พัทลุง", choiceB: "2. กระบี่", choiceC: "3. พัทยา", choiceD: "4. ระยอง", answer: 2))
        list.append(Question(image: "question_mark", questionText: "ชาวซาไกใช้อะไรชุบปลายลูกดอกเพื่อให้เกิดพิษ ?", choiceA: "1. โพแทสเซียม ไซยาไนท์", choiceB: "2. ยางน่อง", choiceC: "3. พิษของดอกไม้", choiceD: "4. พิษของงูเห่า", answer: 2))
        list.append(Question(image: "question_mark", questionText: "ไทยเข้าเป็นภาคีอนุสัญญาว่าด้วยสิทธิเด็กเมื่อปีไหน ?", choiceA: "1. ปี พ.ศ. 2535", choiceB: "2. ปี พ.ศ. 2536", choiceC: "3. ปี พ.ศ. 2537", choiceD: "4. ปี พ.ศ. 2538", answer: 1))
        list.append(Question(image: "panama", questionText: "คลองปานามาเป็นอิสระสิ้นสุดการควบคุมของสหรัฐอเมริกา เมื่อใด ?", choiceA: "1. 14 ธันวาคม พ.ศ. 2542", choiceB: "2. 25 ธันวาคม พ.ศ. 2499", choiceC: "3. 31 ธันวาคม พ.ศ. 1999", choiceD: "4. 32 ธันวาคม พ.ศ. 2561", answer: 1))
        list.append(Question(image: "question_mark", questionText: "ใครเป็นนางเอกหนังไทยคนแรก  ?", choiceA: "1. ยิ่งลักษณ์ ชินวัตร", choiceB: "2. ตั๊ก ศิริพร", choiceC: "3. เสงี่ยม นาวีเสถียร", choiceD: "4. หนูเล็ก ก่อนบ่าย", answer: 3))
        list.append(Question(image: "question_mark", questionText: "ผ้าขะม้าไทยเพี้ยนมาจาก 'จาม่า' ซึ่งเป็นผ้าพาดบ่าของชาติใด ?", choiceA: "1. จาไมก้า", choiceB: "2. สเปน", choiceC: "3. เปอร์เซีย", choiceD: "4. จีน", answer: 3))
        list.append(Question(image: "question_mark", questionText: "นางคอราซอน อาคีโน เป็นประธานาธิบดีหญิงคนแรกของประเทศใด ?", choiceA: "1. ไทย", choiceB: "2. พม่า", choiceC: "3. ฟิลิปปินส์", choiceD: "4. เกาหลีเหนือ", answer: 3))
        list.append(Question(image: "question_mark", questionText: "เทือกเขาแห่งใดยาวที่สุดในโลก ?", choiceA: "1. เทือกเขาเอเวอเรส", choiceB: "2. เทือกเขาเอลฟ์", choiceC: "3. เทือกเขาแอนดีส", choiceD: "4. เทือกเขาแอนตัส", answer: 3))
        list.append(Question(image: "question_mark", questionText: "แหล่งอารยธรรมที่เก่าแก่ที่สุดของจีนอยู่ในลุ่มแม่น้ำใด ?", choiceA: "1. แม่น้ำเจ้าพระยา", choiceB: "2. แม่น้ำไนล์", choiceC: "3. แม่น้ำฮวงโห", choiceD: "4. แม่น้ำแยงซีเกียง", answer: 3))
        list.append(Question(image: "braille", questionText: "ใครสอนเด็กตาพิการของไทยเรียนอักษรเบรลเป็นครั้งแรก ?", choiceA: "1. นางสาวเจนนิเฟอร์ คิ้ม", choiceB: "2. นางสาวเจนนิเฟอร์ ลอว์เลนส์", choiceC: "3. นางสาวเจนนิเฟอร์ คลอเคลีย", choiceD: "4. นางสาวเจนนิเฟอร์ คลอฟิลด์", answer: 4))
        list.append(Question(image: "question_mark", questionText: "อิสราเอลมีพลเมืองนับถือศาสนาใดมากที่สุด ?", choiceA: "1. อิสลาม", choiceB: "2. พุทธ", choiceC: "3. ยิว", choiceD: "4. คริสต์", answer: 3))
        list.append(Question(image: "monalisa", questionText: "ใครซื้อภาพโมนาลิซาเป็นคนแรก ?", choiceA: "1. นายพงศพล อนงค์", choiceB: "2. นายชานนท์ ตรีเมต", choiceC: "3. พระเจ้าฟรานซิสที่ 1", choiceD: "4. โมนาลิซา เป็นนักดนตรี", answer: 3))
        list.append(Question(image: "question_mark", questionText: "วันจันทร์แรกของเดือนตุลาคมทุกปี เป็นวันสำคัญอย่างไรต่อชาวโลก ?", choiceA: "1. วันเอดส์โลก", choiceB: "2. วันสตรีโลก", choiceC: "3. วันที่อยู่อาศัยโลก", choiceD: "4. วันธรรมดาวันหนึ่งไม่มีอะไรพิเศษ", answer: 3))
        list.append(Question(image: "question_mark", questionText: "อัลเฟรดมหาราช เป็นมหาราชองค์เดียวของประเทศใด ?", choiceA: "1. เลบานอน", choiceB: "2. อังกฤษ", choiceC: "3. รัสเซีย", choiceD: "4. จอร์เจีย", answer: 2))
        list.append(Question(image: "eden", questionText: "ตำนานว่าด้วยกำเนิดมนุษย์ในพระคัมภีร์ไบเบิลอยู่ที่ไหน ?", choiceA: "1. สวนสาธารณะ", choiceB: "2. สวนอีเด็น", choiceC: "3. สวนรถไฟ", choiceD: "4. สวนผัก", answer: 2))
        list.append(Question(image: "kodak", questionText: "ใครประดิษฐ์กล้องถ่ายรูปโกดัก ?", choiceA: "1. ยอร์จ โกดัก", choiceB: "2. ยอร์จ อีสต์แมน", choiceC: "3. พงศพล โกดัก", choiceD: "4. โกดัก อีสต์แมน", answer: 2))
        list.append(Question(image: "question_mark", questionText: "ใครปลดปล่อยยิวจากการเป็นทาสของอียิปต์โบราณ ?", choiceA: "1. โมเศส", choiceB: "2. โมเสส", choiceC: "3. โมเสษ", choiceD: "4. โมเสพ", answer: 2))
        list.append(Question(image: "question_mark", questionText: "ยุคหินแบ่งเป็น 3 ยุค มียุคอะไร  ?", choiceA: "1. ยุคหินเก่า, หินกลาง และหินใหม่", choiceB: "2. ยุคหิน,เหล็ก,ไฟ", choiceC: "3. ยุคหินเก่า,หินใหม่,สำริด", choiceD: "4. ยุคหินเก่า,หินใหม่,ยุคเหล็ก", answer: 1))
        list.append(Question(image: "koleah", questionText: "เรือกอและในแถบจังหวัดภาคใต้ตอนล่างใช้ประโยชน์อะไร ?", choiceA: "1. เป็นเรือท่องเที่ยว", choiceB: "2. เป็นชื่อเรือรบ", choiceC: "3. เป็นเรือของชาวบ้าน", choiceD: "4. เป็นเรือประมง", answer: 4))

    }
}
